/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard.agents'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard.approvals'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard.compliance'
import { Route as DashboardWalletsRouteImport } from './routes/dashboard.wallets'

const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/dashboard/agents',
  path: '/dashboard/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/dashboard/approvals',
  path: '/dashboard/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/dashboard/compliance',
  path: '/dashboard/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletsRoute = DashboardWalletsRouteImport.update({
  id: '/dashboard/wallets',
  path: '/dashboard/wallets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard/agents'
    | '/dashboard/approvals'
    | '/dashboard/compliance'
    | '/dashboard/wallets'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard/agents'
    | '/dashboard/approvals'
    | '/dashboard/compliance'
    | '/dashboard/wallets'
    | '/dashboard'
  id:
    | '__root__'
    | '/dashboard/agents'
    | '/dashboard/approvals'
    | '/dashboard/compliance'
    | '/dashboard/wallets'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardWalletsRoute: typeof DashboardWalletsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/dashboard/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/dashboard/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/dashboard/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallets': {
      id: '/dashboard/wallets'
      path: '/dashboard/wallets'
      fullPath: '/dashboard/wallets'
      preLoaderRoute: typeof DashboardWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardWalletsRoute: DashboardWalletsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
