/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as ComplianceStandardsRouteImport } from './routes/compliance-standards'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleBenefitsRouteImport } from './routes/$locale.benefits'
import { Route as LocaleComplianceStandardsRouteImport } from './routes/$locale.compliance-standards'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleFaqRouteImport } from './routes/$locale.faq'
import { Route as LocaleIndustriesRouteImport } from './routes/$locale.industries'
import { Route as LocalePricingRouteImport } from './routes/$locale.pricing'
import { Route as LocaleProductRouteImport } from './routes/$locale.product'
import { Route as LocaleRoiCalculatorRouteImport } from './routes/$locale.roi-calculator'
import { Route as LocaleSecurityRouteImport } from './routes/$locale.security'
import { Route as LocaleSolutionsRouteImport } from './routes/$locale.solutions'
import { Route as LocaleUseCasesRouteImport } from './routes/$locale.use-cases'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard.agents'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard.approvals'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard.compliance'
import { Route as DashboardWalletsRouteImport } from './routes/dashboard.wallets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceStandardsRoute = ComplianceStandardsRouteImport.update({
  id: '/compliance-standards',
  path: '/compliance-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBenefitsRoute = LocaleBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleComplianceStandardsRoute =
  LocaleComplianceStandardsRouteImport.update({
    id: '/compliance-standards',
    path: '/compliance-standards',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFaqRoute = LocaleFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleIndustriesRoute = LocaleIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePricingRoute = LocalePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductRoute = LocaleProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRoiCalculatorRoute = LocaleRoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSecurityRoute = LocaleSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSolutionsRoute = LocaleSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleUseCasesRoute = LocaleUseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => LocaleRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletsRoute = DashboardWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/benefits': typeof BenefitsRoute
  '/compliance-standards': typeof ComplianceStandardsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRoute
  '/use-cases': typeof UseCasesRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/benefits': typeof LocaleBenefitsRoute
  '/$locale/compliance-standards': typeof LocaleComplianceStandardsRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/industries': typeof LocaleIndustriesRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/product': typeof LocaleProductRoute
  '/$locale/roi-calculator': typeof LocaleRoiCalculatorRoute
  '/$locale/security': typeof LocaleSecurityRoute
  '/$locale/solutions': typeof LocaleSolutionsRoute
  '/$locale/use-cases': typeof LocaleUseCasesRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benefits': typeof BenefitsRoute
  '/compliance-standards': typeof ComplianceStandardsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRoute
  '/use-cases': typeof UseCasesRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/benefits': typeof LocaleBenefitsRoute
  '/$locale/compliance-standards': typeof LocaleComplianceStandardsRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/industries': typeof LocaleIndustriesRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/product': typeof LocaleProductRoute
  '/$locale/roi-calculator': typeof LocaleRoiCalculatorRoute
  '/$locale/security': typeof LocaleSecurityRoute
  '/$locale/solutions': typeof LocaleSolutionsRoute
  '/$locale/use-cases': typeof LocaleUseCasesRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/$locale': typeof LocaleIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/benefits': typeof BenefitsRoute
  '/compliance-standards': typeof ComplianceStandardsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRoute
  '/use-cases': typeof UseCasesRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/benefits': typeof LocaleBenefitsRoute
  '/$locale/compliance-standards': typeof LocaleComplianceStandardsRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/faq': typeof LocaleFaqRoute
  '/$locale/industries': typeof LocaleIndustriesRoute
  '/$locale/pricing': typeof LocalePricingRoute
  '/$locale/product': typeof LocaleProductRoute
  '/$locale/roi-calculator': typeof LocaleRoiCalculatorRoute
  '/$locale/security': typeof LocaleSecurityRoute
  '/$locale/solutions': typeof LocaleSolutionsRoute
  '/$locale/use-cases': typeof LocaleUseCasesRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/wallets': typeof DashboardWalletsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/benefits'
    | '/compliance-standards'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/industries'
    | '/pricing'
    | '/product'
    | '/roi-calculator'
    | '/security'
    | '/solutions'
    | '/use-cases'
    | '/$locale/about'
    | '/$locale/benefits'
    | '/$locale/compliance-standards'
    | '/$locale/contact'
    | '/$locale/faq'
    | '/$locale/industries'
    | '/$locale/pricing'
    | '/$locale/product'
    | '/$locale/roi-calculator'
    | '/$locale/security'
    | '/$locale/solutions'
    | '/$locale/use-cases'
    | '/dashboard/agents'
    | '/dashboard/approvals'
    | '/dashboard/compliance'
    | '/dashboard/wallets'
    | '/$locale/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/benefits'
    | '/compliance-standards'
    | '/contact'
    | '/faq'
    | '/industries'
    | '/pricing'
    | '/product'
    | '/roi-calculator'
    | '/security'
    | '/solutions'
    | '/use-cases'
    | '/$locale/about'
    | '/$locale/benefits'
    | '/$locale/compliance-standards'
    | '/$locale/contact'
    | '/$locale/faq'
    | '/$locale/industries'
    | '/$locale/pricing'
    | '/$locale/product'
    | '/$locale/roi-calculator'
    | '/$locale/security'
    | '/$locale/solutions'
    | '/$locale/use-cases'
    | '/dashboard/agents'
    | '/dashboard/approvals'
    | '/dashboard/compliance'
    | '/dashboard/wallets'
    | '/$locale'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/benefits'
    | '/compliance-standards'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/industries'
    | '/pricing'
    | '/product'
    | '/roi-calculator'
    | '/security'
    | '/solutions'
    | '/use-cases'
    | '/$locale/about'
    | '/$locale/benefits'
    | '/$locale/compliance-standards'
    | '/$locale/contact'
    | '/$locale/faq'
    | '/$locale/industries'
    | '/$locale/pricing'
    | '/$locale/product'
    | '/$locale/roi-calculator'
    | '/$locale/security'
    | '/$locale/solutions'
    | '/$locale/use-cases'
    | '/dashboard/agents'
    | '/dashboard/approvals'
    | '/dashboard/compliance'
    | '/dashboard/wallets'
    | '/$locale/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  BenefitsRoute: typeof BenefitsRoute
  ComplianceStandardsRoute: typeof ComplianceStandardsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  SecurityRoute: typeof SecurityRoute
  SolutionsRoute: typeof SolutionsRoute
  UseCasesRoute: typeof UseCasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-standards': {
      id: '/compliance-standards'
      path: '/compliance-standards'
      fullPath: '/compliance-standards'
      preLoaderRoute: typeof ComplianceStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/benefits': {
      id: '/$locale/benefits'
      path: '/benefits'
      fullPath: '/$locale/benefits'
      preLoaderRoute: typeof LocaleBenefitsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/compliance-standards': {
      id: '/$locale/compliance-standards'
      path: '/compliance-standards'
      fullPath: '/$locale/compliance-standards'
      preLoaderRoute: typeof LocaleComplianceStandardsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/faq': {
      id: '/$locale/faq'
      path: '/faq'
      fullPath: '/$locale/faq'
      preLoaderRoute: typeof LocaleFaqRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/industries': {
      id: '/$locale/industries'
      path: '/industries'
      fullPath: '/$locale/industries'
      preLoaderRoute: typeof LocaleIndustriesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/pricing': {
      id: '/$locale/pricing'
      path: '/pricing'
      fullPath: '/$locale/pricing'
      preLoaderRoute: typeof LocalePricingRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/product': {
      id: '/$locale/product'
      path: '/product'
      fullPath: '/$locale/product'
      preLoaderRoute: typeof LocaleProductRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/roi-calculator': {
      id: '/$locale/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/$locale/roi-calculator'
      preLoaderRoute: typeof LocaleRoiCalculatorRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/security': {
      id: '/$locale/security'
      path: '/security'
      fullPath: '/$locale/security'
      preLoaderRoute: typeof LocaleSecurityRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/solutions': {
      id: '/$locale/solutions'
      path: '/solutions'
      fullPath: '/$locale/solutions'
      preLoaderRoute: typeof LocaleSolutionsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/use-cases': {
      id: '/$locale/use-cases'
      path: '/use-cases'
      fullPath: '/$locale/use-cases'
      preLoaderRoute: typeof LocaleUseCasesRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallets': {
      id: '/dashboard/wallets'
      path: '/wallets'
      fullPath: '/dashboard/wallets'
      preLoaderRoute: typeof DashboardWalletsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleBenefitsRoute: typeof LocaleBenefitsRoute
  LocaleComplianceStandardsRoute: typeof LocaleComplianceStandardsRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleFaqRoute: typeof LocaleFaqRoute
  LocaleIndustriesRoute: typeof LocaleIndustriesRoute
  LocalePricingRoute: typeof LocalePricingRoute
  LocaleProductRoute: typeof LocaleProductRoute
  LocaleRoiCalculatorRoute: typeof LocaleRoiCalculatorRoute
  LocaleSecurityRoute: typeof LocaleSecurityRoute
  LocaleSolutionsRoute: typeof LocaleSolutionsRoute
  LocaleUseCasesRoute: typeof LocaleUseCasesRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleBenefitsRoute: LocaleBenefitsRoute,
  LocaleComplianceStandardsRoute: LocaleComplianceStandardsRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleFaqRoute: LocaleFaqRoute,
  LocaleIndustriesRoute: LocaleIndustriesRoute,
  LocalePricingRoute: LocalePricingRoute,
  LocaleProductRoute: LocaleProductRoute,
  LocaleRoiCalculatorRoute: LocaleRoiCalculatorRoute,
  LocaleSecurityRoute: LocaleSecurityRoute,
  LocaleSolutionsRoute: LocaleSolutionsRoute,
  LocaleUseCasesRoute: LocaleUseCasesRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardWalletsRoute: typeof DashboardWalletsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardWalletsRoute: DashboardWalletsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  BenefitsRoute: BenefitsRoute,
  ComplianceStandardsRoute: ComplianceStandardsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  SecurityRoute: SecurityRoute,
  SolutionsRoute: SolutionsRoute,
  UseCasesRoute: UseCasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
